# Generated by Django 4.2.23 on 2025-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('exchange_token', models.CharField(blank=True, max_length=50, null=True)),
                ('tradingsymbol', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=50, null=True)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
