# Generated by Django 4.2.23 on 2025-06-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(db_index=True, max_length=100)),
                ('tracking_date', models.DateField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-tracking_date'],
            },
        ),
    ]
