# Generated by Django 4.2.23 on 2025-06-30 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_trackedstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PLANNED', max_length=10)),
                ('planned_entry_price', models.FloatField(blank=True, null=True)),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
                ('target_price', models.FloatField(blank=True, null=True)),
                ('actual_entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trade_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-trade_date'],
            },
        ),
        migrations.DeleteModel(
            name='TrackedStock',
        ),
        migrations.AddField(
            model_name='radaralert',
            name='source_strategy',
            field=models.CharField(db_index=True, default='legacy_scan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='radaralert',
            unique_together={('instrument_key', 'source_strategy')},
        ),
    ]
