# Generated by Django 4.2.23 on 2025-07-01 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0004_tradelog_delete_trackedstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='trade_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
