# Generated by Django 4.2.23 on 2025-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='average_volume',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
