# Generated by Django 4.2.23 on 2025-07-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_add_historical_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='radaralert',
            name='alert_type',
            field=models.CharField(db_index=True, default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='radaralert',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='radaralert',
            name='notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='radaralert',
            name='priority',
            field=models.CharField(db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='radaralert',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
