# Generated by Django 4.2.23 on 2025-07-05 20:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading_app', '0010_radaralert_alert_type_radaralert_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(max_length=100)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('avg_entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unrealized_pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(max_length=100)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=12)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.AlterModelOptions(
            name='radaralert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tradelog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='radaralert',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='exchange_token',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='tick_size',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='actual_entry_price',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='planned_entry_price',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='stop_loss_price',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='target_price',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_app.instrument'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='average_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='segment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tradingsymbol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='alert_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='alert_type',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('ENTRY', 'Entry')], default='SCREENING', max_length=20),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='indicators',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='source_strategy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TRIGGERED', 'Triggered'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='radaralert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='instrument_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='notes',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualtrade',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_trades', to='trading_app.radaralert'),
        ),
        migrations.AddField(
            model_name='virtualtrade',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading_app.virtualwallet'),
        ),
        migrations.AddField(
            model_name='virtualposition',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading_app.virtualwallet'),
        ),
        migrations.AlterUniqueTogether(
            name='virtualposition',
            unique_together={('wallet', 'instrument_key')},
        ),
    ]
