# Generated by Django 4.2.23 on 2025-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0011_virtualposition_virtualtrade_virtualwallet_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='radaralert',
            constraint=models.UniqueConstraint(fields=('instrument_key', 'source_strategy'), name='unique_instrument_strategy'),
        ),
    ]
